apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.imageMosquitto.name}}
  labels:
    app: {{.Values.imageMosquitto.name}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.Values.imageMosquitto.name}}
  template:
    metadata:
      labels:
        app: {{.Values.imageMosquitto.name}}
    spec:
      containers:
        - name: mqtt
          image: {{.Values.imageMosquitto.repository}}:{{.Values.imageMosquitto.tag}}
          imagePullPolicy: {{.Values.imageMosquitto.pullPolicy}}
          args: {{.Values.imageMosquitto.args}}
          ports:
            - name: default
              containerPort: {{.Values.imageMosquitto.port}}
              protocol: TCP
            - name: websocket
              containerPort: {{.Values.imageMosquitto.websocketPort}}
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.imageMosquitto.name}}
  labels:
    app: {{.Values.imageMosquitto.name}}
spec:
  type: ClusterIP
  selector:
    app: {{.Values.imageMosquitto.name}}
  ports:
    - port: {{.Values.imageMosquitto.port}}
      targetPort: default
      name: default
      protocol: TCP
    - port: {{.Values.imageMosquitto.websocketPort}}
      targetPort: websocket
      name: websocket
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.imageMosquitto.name}}-nodeport
spec:
  type: NodePort
  selector:
    app: {{.Values.imageMosquitto.name}}
  ports:
  - port: {{.Values.imageMosquitto.port}}
    targetPort: {{.Values.imageMosquitto.port}}
    nodePort: {{.Values.imageMosquitto.nodePort}}
